version: 0.0
os: linux

files:
- source: files/index.html
destination: /var/ww/html

permissions:
- object: /var/www/html
pattern: index.html
owner: apache
mode: 644
type:
- file 
hooks:
beforeInstall:
- location: scripts/webserver-stop.sh
- location: scripts/delete-old-index.sh
AfterInstall:
- location: scripts/sleep.sh
- location/webserver-start.sh
